= Настройка разметок

xref:install.adoc[Установленный] {sc} может быть запущен в режиме конструктора разметок. В данном случае открывается страницы настройки формы.

Страница состоит из трёх колонок со следющими панелями:

* _Библиотека элементов_ -- область содержит элементы разметок, досупные для добавления в карточку. Область может быть скрыта пользователем.
* _Дизайн формы_ -- основная рабочая область, в которой настраиваются разметки. Область занимает все предоставленное место.
* _Свойства_ -- свойства выбранного элемента управления. Область может быть скрыта пользователем.

При нажатии кнопки *Опубликовать* в БД разработки будут загружены все необходимые данные для того, чтобы отобразить эту разметку в интефейсе {wc}а:

* При первичной публикации будет добавлена новая разметка
* При повторных публикациях существующая разметка будет перезаписана

== Библиотека элементов

{sc} при настройке разметки позволяет оперировать сразу полями карточки. При перетаскивании элемента из библиотеки в разметку добавляется сразу поле карточки со связаным источником данных, элемент управления при этом определяется автомтаически.

.В библиотеке отображается:
. Список компонент, представленный следующими компонентами:
+
* Блок
* Метка
+
. Раздел полей карточки. {sc} позволяет настроить разметку для единственного типа карточки, назначенного для Приложения. В разделе отображается список полей этой карточки. Тип элемента управления определяется автоматически по типу поля карточки.

== Дизайн формы

Область карточки, представляет разметку карточку, в которую добавляются элементы управления. Область максимально приближена к итоговому виду разметки в {wc}е. Элементы добавляются путём перетаскивания из библиотеки элементов.

Для элемента, на котором установлен фокус в Панели дизайна, справа, на Панели свойств отображаются доступные для настройки свойства ЭУ.

При перетаскивании ЭУ из библиотеки отображается занимаемое им место. По умолчанию Эу занимает всю доступную ширину блока, в который он добавляется. Блоки могут быть размещены рядом друг с другом, ширина блоков определяется автоматически. Если необходимо, размер блока может быть изменён вручную. При удалении, перемещении занимаемое место автоматически распределяется между существующими элементами.

При помощи специальных кнопок можно изменить масштаб отображения формы и тип устройства с перестроением настроенной формы: десктоп, смартфон, планшет.

== Панель свойств

Панель отображает свойства выбранного в панели Дизайна формы ЭУ. Значения свойств могуи быть изменены. Выполненные изменения применяются сразу.
