= Копировать и вставить вид

Копировать разрешается только виды, имеющие собственные настройки в _Конструкторе карточек_. При выполнении операции все настройки вида будут скопированы в новый вид.

Если у копируемого вида присутствовали настроенные xref:card-create-mode.adoc[режимы создания], после вставки вида все режимы будут скопированы в новый вид.

.Чтобы скопировать вид:
. Выберите в _Дереве видов карточек_ вид, который требуется скопировать.
. Вызовите контекстное меню правой кнопкой мыши и выберите команду *Копировать вид*.
+
Настройки вида будут скопированы. В контекстном меню станет активной команда *Вставить вид*.
+
. Выберите в _Дереве видов карточек_ вид, для которого требуется добавить скопированный вид в качестве дочернего.
. В контекстном меню вида выберите команду *Вставить вид*.
+
Вид будет добавлен в выбранную ветку дерева. Название скопированного вида будет автоматически сформировано как `Название скопированного вида + N`, где `N` -- номер ранее созданного вида (если не было задано другое название).
